Skgrid minor
ohsu-comp-bio/gdan-tmp-models pull request #32
Opened 2022-06-07 23:38 UTC by jordan2lee

skgrid will train models from an algorithm found in it's classifier config file (cleaner, can point to a file for the skgrid model lib options easily, etc)

streamline dockerfile and add new classifier config file

2022-06-07 23:42 UTC, kellrott requested changes

2022-06-07 23:42 UTC, kellrott commented on skgrid/Dockerfile
> +RUN chmod 777 ./mlib.sh ./predict.sh ./train.sh ./run_train.py
Why does this need to be done in the dockerfile?

2022-06-07 23:42 UTC, kellrott commented on skgrid/run_train.py
> +        d['kernel'] = eval(classifier_config['gp_kernels'][d['kernel']])()
A bare 'eval' on a config file is considered a bad security process

2022-06-07 23:42 UTC, kellrott commented on skgrid/run_train.py
> +    with open("/skgrid/config_classifier.json", 'r') as fh:
Why is this not configurable?

2022-06-07 23:42 UTC, kellrott commented on skgrid/run_train.py
> -classifers = {
What is the reasoning for moving this code to a config file? These link to the actual classes, which can't be serialized to JSON

2022-06-08 17:16 UTC, jordan2lee commented
closing because better method is to keep classifier info in the source file rather than separate it into a sep config file

2022-06-08 17:16 UTC, closed without merging